### ISSUE TITLE
Add api/search/latestVersion

### ISSUE THREAD

**Issue by igreenfield** [JFrogDev/artifactory-client-java#106]
Artifactory api has 'api/search/latestVersion' but the sreach client miss this.

could you add this to the client?

thanks

**Comment by eyalbe4** [comment]
Sure @igreenfield. We would like add this. Would you like to help us get this into the client sooner and submit a pull request?

**Comment by igreenfield** [comment]
@eyalbe4 create pull request #109

**Comment by eyalbe4** [comment]
Thank you for this @igreenfield. 
Let's continue discussing this inside #109.
