### ISSUE TITLE
java.lang.NoClassDefFoundError: java/util/function/Consumer

### ISSUE THREAD

**Issue by oscarpic** [JFrogDev/artifactory-client-java#110]
Hello I'm using maven and Java 1.7, in execution time, when calls to ArtifactoryClient.create,  I´m having this error: java.lang.NoClassDefFoundError: java/util/function/Consumer

**Comment by axel3rd** [comment]
+1 on this item. Java 8 is required at runtime since v2.3.3. This is IMO a most important impact for a minor version upgrade :(

**Comment by romangurevitch** [comment]
Thanks for reporting this @oscarpic, @axel3rd.
We have released version 2.3.4 which fixes the issue.

**Comment by axel3rd** [comment]
I confirm it (v2.3.4) works with Java 7 at runtime. Many thanks for this rapid fix ! This issue could be closed :)
