### ISSUE TITLE
Adding getters to the repository builder classes

### ISSUE THREAD

**Issue by fritaly** [JFrogDev/artifactory-client-java#124]
I'm currently using the different repository builder classes (`RepositoryBuilder`, `VirtualRepositoryBuilder`, `LocalRepositoryBuilder`, etc) to implement some automation in Artifactory.

The automation consists in implementing some generic rules (Example: "All remote repos should be online") which operate on the AF repositories. When a violation to the rule is detected, the rule automatically reconfigures the repository to fix the issue (thanks to the builder class) and commits the change to AF. Rules are meant to be very simple and we want to apply lots of different rules to configure the AF server.

However, I have identified that the lack of getters on the different repository builder classes makes it difficult to implement those rules. Because the builder class doesn't allow me to read the configuration currently stored in the builder instance, it's not possible for me to apply incremental changes to the configuration of a repository.

I hope the following pseudo-code will shed some light.

```
// Retrieve the rules to apply to the virtual repos
def rules = getVirtualRepositoryRules() as List<VirtualRepositoryRule>

// Loop over all the virtual repos in AF
virtualRepos.each { repository ->
  // Backup the repository configuration to detect changes (not detailed)

  // Create a builder class to allow rules to reconfigure the repository (if necessary)
  VirtualRepositoryBuilder builder = artifactory.repositories().builders()
    .builderFrom(repository)
    .repositorySettings(repository.repositorySettings)
    .xraySettings(repository.xraySettings)

  // Apply all the rules to the current virtual repository
  rules.each { rule ->
    rule.apply(repository, builder)
  }

  // Build the updated configuration
  def updatedConfiguration = configuration.build()

  // Compare the initial and update configurations (not detailed)
  def changeDetected = ...

  if (changeDetected) {
    // Submit the changes to AF
    artifactory.repositories().update(updatedConfiguration)
  }
}
```

In the scenario above, the same `builder` object is passed to different rule objects and "accumulates" the changes applied by the different rules (the first rule can apply some changes, the second rule can apply other changes, etc). 

This approach cannot work because the repository builder classes only offer setter methods. The lack of getter methods makes it impossible for the second rule to see the changes introduced by the first rule (they're not yet applied to the server).

I hope this makes sense.

For instance, the change would consist in adding the following getters to the class `VirtualRepositoryBuilderImpl`.

```
Collection<String> getRepositories() {
    this.repositories
}

boolean isArtifactoryRequestsCanRetrieveRemoteArtifacts() {
    this.artifactoryRequestsCanRetrieveRemoteArtifacts
}

String getDefaultDeploymentRepo() {
    this.defaultDeploymentRepo
}
```

I'm willing to contribute a PR if you think this request makes sense.

**Comment by eyalbe4** [comment]
Sounds good @fritaly.
Please go ahead and create a pull request for this. Thanks.

**Comment by fritaly** [comment]
Thanks @eyalbe4, I just created this [PR](https://github.com/JFrogDev/artifactory-client-java/pull/125)
