### ISSUE TITLE
Gradle Artifactory plugin does not support multi-module project as well

### ISSUE THREAD

**Issue by imanushin** [JFrogDev/artifactory-client-java#172]
Gradle supports multimodule project (see in [official doc](https://docs.gradle.org/current/userguide/multi_project_builds.html)).

This is useful when you try to decompose solid project to modules (for example, to have different modules - server, client, model).

However, gradle artifactory plugin is unable to publish build info for subprojects.

So, in my example:
1. Root project does not have any dependency (it is just container)
2. Subprojects are ordinal java projects
3. Each subproject has artifactoryPublish task
4. After calling ```.\gradlew.bat :artifactoryPublish```

*Expected result:*
All modules are published, build info is published to each module (or build info has unified data of all submodules)

*Actual result:*
All modules are published. No build info was published to artifactory

**Comment by eyalbe4** [comment]
@imanushin
Would you like to move this discussion to the gradle-artifactory-plugin github repo? It is under
https://github.com/JFrogDev/build-info
This repo includes the code of the java client for Artifactory.
Thanks

**Comment by imanushin** [comment]
Agree, created issue in the another repo - https://github.com/JFrogDev/build-info/issues/145
