### ISSUE TITLE
Version 2.3.5 doesn't contain ArtifactoryClientBuilder

### ISSUE THREAD

**Issue by elektrovert** [JFrogDev/artifactory-client-java#179]
Hi there, 
I'm just trying to get your examples working, but it appears version 2.3.5 doesn't contain the `ArtifactoryClientBuilder ` class file. Are the examples obsolete?

**Comment by eyalbe4** [comment]
@elektrovert,
The upcoming release of the client will include the builder.
We applogise for the confusion. Following the release, the master branch (and the README) will be always up to date with the latest release.

**Comment by elektrovert** [comment]
OK, thanks for the quick reply!
