### ISSUE TITLE
Documentation for listing repositories with Java client is unclear

### ISSUE THREAD

**Issue by enzeart** [JFrogDev/artifactory-client-java#187]
**From the documentation:**
`java List<LightweightRepository> repoList = artifactory.repositories().list(LOCAL);`

**Issue:**
It's unclear as to what LOCAL is referring to in this context. I've tried digging through the source code with my IDE to figure out what to pass into this method call to no avail.

**Comment by enzeart** [comment]
The values for this method can be found in the org.jfrog.artifactory.client.model.impl.RepositoryTypeImpl enum.

**Comment by eyalbe4** [comment]
@enzeart,
Would you like to submit a pull request to improve the documentation?

**Comment by enzeart** [comment]
@eyalbe4 
Sorry it took me a while to get back to you. I'd love to contribute! Please see the referenced pull request and let me know if there are any issues.

#188

**Comment by eyalbe4** [comment]
Thanks @enzeart. Merged :)
