### ISSUE TITLE
Feature request: support for GAVC search/Artifact Version search

### ISSUE THREAD

**Issue by davidmc24** [JFrogDev/artifactory-client-java#52]
I'm working on a tool that will be periodically searching Artifactory for new versions of specific group/artifact coordinates.  Based on my perusal of the Artifactory REST API docs, it looks like either of these search types may be good enough for my use case, however neither appears to currently be supported by the Java client library.

http://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-GAVCSearch
http://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ArtifactVersionSearch

In a perfect world, I'd like for the search endpoints to also support filtering by create date.  I suppose I'll handle that client-side for now.

**Comment by ljohnston** [comment]
+1

This client isn't particularly useful to us without this capability.

**Comment by eyalbe4** [comment]
Thanks. We will soon add GAVC search to the java-client.

**Comment by padyx** [comment]
Should we close now that PR #86 was merged?

**Comment by eyalbe4** [comment]
Yes, @padyx. Closing this one. Thanks!
