### ISSUE TITLE
There is no "principals" for the permission target builder

### ISSUE THREAD

**Issue by anastasiyam** [JFrogDev/artifactory-client-java#54]
While i try to create new permission target i have no way to add user and group with permissions, cause it use the item permission and it's doesn't match the json file.
json file:
{
- "name": "populateCaches",
- "includesPattern": "**" (default),
- "excludesPattern": "" (default),
- "repositories": ["local-rep1", "local-rep2", "remote-rep1", "virtual-rep2"],
- "principals": {
      "users" : {
        "bob": ["r","w","m"],
        "alice" : ["d","w","n", "r"]
      },
      "groups" : {
        "dev-leads" : ["m","r","n"],
        "readers" : ["r"]
      }
  }
  }

what we get:
{
   "name": "test1",
   "includesPattern": "**" ,
   "excludesPattern": "" ,
   "repositories": ["new-local"],
   "itemPermissions": {
        "users" : {
          "test1": ["r","w","m"],
          "test2" : ["d","w","n", "r"],
          "test3" : ["r"]
        },
          "groups" : {
          "deployers" : ["m","r","n"],
          "users" : ["r"]
        }
    }
}

**Comment by axel3rd** [comment]
+1

**Comment by axel3rd** [comment]
Could be closed, will be fixed in v2.3.2 (commit [c152a39](https://github.com/JFrogDev/artifactory-client-java/commit/c152a397bfb927c795aa5a8885a59038664e4f72)).
