### ISSUE TITLE
Missing documentation/example for downloading artifacts from artifactory

### ISSUE THREAD

**Issue by bartoszwalacik** [JFrogDev/artifactory-client-java#65]
Hi Guys,
does your clinet support downloading artifacts? Where can I find example or documentation how to do it?

**Comment by eyalbe4** [comment]
Hi @bartoszwalacik ,
Yes, download and upload are supported by the artifactory-client-java.
Please have a look at the DownloadUploadTests class as part of the client code, to see examples for how it can be done (the testDownloadWithoutProperties() method for example).

**Comment by bartoszwalacik** [comment]
thanx, thats what I was looking for
