### ISSUE TITLE
Add Storage Summary support

### ISSUE THREAD

**Issue by eyalbe4** [JFrogDev/artifactory-client-java#67]
Add support for the "Get Storage Summary Info" Artifactpry REST API (/api/storageinfo)

**Comment by axel3rd** [comment]
@eyalbe4:  IMO : Coud be marked as fixed if #97 merged.

Furthermore, I promote #94, I really need it ^^ (and there is many activity on plugin these days)

**Comment by eyalbe4** [comment]
Thanks @axel3rd!
Closing this issue.

**Comment by axel3rd** [comment]
Thanks for the merge.
