### ISSUE TITLE
Full support of external group

### ISSUE THREAD

**Issue by axel3rd** [JFrogDev/artifactory-client-java#90]
Hi,

When you have linked Artifactory to an LDAP and you want inject some groups with API (before inject some permission, for preload all security stuff before user login), you can't.

Mainly because you can't fill **realmAttributes** (and **realm**)

A workaround is to extend `GroupImpl` and add this management in it ... but it would be simpler if this parameters could be used in `GroupBuilder`.

``
artifactory.security().createOrUpdateGroup(myGroupRealmImpl);
``

Best regards

**Comment by romangurevitch** [comment]
@axel3rd, thanks for your pull request, with your permission I'm closing the issue.

**Comment by axel3rd** [comment]
:+1:
